version: '3'
services:
  nginx:
    build: docker/nginx
    ports:
      - "8001:80"
    links:
      - "php:php"
    volumes:
      - "./web:/var/www/app/public:rw"
      - "./docker/nginx/config/dev.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
    ports:
      - "9001"
    volumes:
      - "./:/var/www/app:rw"
      - "./docker/php/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    links:
      - "db:db"
    depends_on:
      - db
  db:
    build:
      context: ./docker/mariadb
    restart: always
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:8080
  mailer:
    build:
      context: ./docker/maildev
    ports:
      - "1080"
      - "1025"
