blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

seo:
    resource: "@SeoBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

