homepage:
    path:     /
    defaults: { _controller: SeoBundle:Default:index }

photo:
    path:     /photos
    defaults: { _controller: SeoBundle:Media:list }

add:
    path:     /photos/add
    defaults: { _controller: SeoBundle:Media:add }
